<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Films;
use App\Models\Genres;
use App\Models\Loans;
use App\Models\User;
use Illuminate\Support\Facades\Schema;

class FilmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Films::truncate();
        Schema::enableForeignKeyConstraints();
        Films::upsert(
            [
                [
                    'tytul' => 'Skazani na Shawshank',
                    'rezyser' => 'Frank Darabont',
                    'genres_id' => '1',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '1994',
                    'czas_trwania' => '82',
                    'ocena' => '8.4',
                    'opis' => 'Adaptacja opowiadania Stephena Kinga. Niesłusznie skazany na dożywocie bankier, stara się przetrwać w brutalnym, więziennym świecie.',
                    'link_grafika' => 'storage/img/mk1.jpg',
                    'link_film' => 'https://www.youtube.com/embed/3TGpUNWUREQ',
                    'cena' => '20',
                ],
                [
                    'tytul' => 'Forrest Gump',
                    'rezyser' => 'Robert Zemeckis',
                    'genres_id' => '6',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '1994',
                    'czas_trwania' => '84',
                    'ocena' => '7.6',
                    'opis' => 'Historia życia Forresta, chłopca o niskim ilorazie inteligencji z niedowładem kończyn, który staje się miliarderem i bohaterem wojny w Wietnamie.',
                    'link_grafika' => 'storage/img/mk2.jpg',
                    'link_film' => 'https://www.youtube.com/embed/74nR_ePpfXo',
                    'cena' => '18',
                ],
                [
                    'tytul' => 'Władca Pierścieni',
                    'rezyser' => 'Peter Jackson',
                    'genres_id' => '3',
                    'produkcja' => 'Nowa Zelandia',
                    'rok_produkcji' => '2003',
                    'czas_trwania' => '141',
                    'ocena' => '8.2',
                    'opis' => 'Zwieńczenie filmowej trylogii wg powieści Tolkiena. Aragorn jednoczy siły Śródziemia, szykując się do bitwy, która ma odwrócić uwagę Saurona od podążających w kierunku Góry Przeznaczenia hobbitów.',
                    'link_grafika' => 'storage/img/mk3.jpg',
                    'link_film' => 'https://www.youtube.com/embed/a3Qfgn11aHw',
                    'cena' => '15',
                ],
                [
                    'tytul' => 'Lista Schindlera',
                    'rezyser' => 'Steven Spielberg',
                    'genres_id' => '7',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '1993',
                    'czas_trwania' => '135',
                    'ocena' => '7.8',
                    'opis' => 'Historia przedsiębiorcy Oskara Schindlera, który podczas II wojny światowej uratował przed pobytem w obozach koncentracyjnych 1100 Żydów.',
                    'link_grafika' => 'storage/img/mk4.jpg',
                    'link_film' => 'https://www.youtube.com/embed/QQhvww-c5Ms',
                    'cena' => '22',
                ],
                [
                    'tytul' => 'Django',
                    'rezyser' => 'Quentin Tarantino',
                    'genres_id' => '1',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2012',
                    'czas_trwania' => '165',
                    'ocena' => '8.2',
                    'opis' => 'Łowca nagród Schultz i czarnoskóry niewolnik Django wyruszają w podróż, aby odbić żonę tego drugiego z rąk bezlitosnego Calvina Candieego.',
                    'link_grafika' => 'storage/img/mk5.jpg',
                    'link_film' => 'https://www.youtube.com/embed/fmwcCsS0-YM',
                    'cena' => '24',
                ],
                [
                    'tytul' => 'Coco',
                    'rezyser' => 'Adrian Molina',
                    'genres_id' => '4',
                    'produkcja' => 'Kanada',
                    'rok_produkcji' => '2018',
                    'czas_trwania' => '105',
                    'ocena' => '8.3',
                    'opis' => 'Dwunastoletni meksykański chłopiec imieniem Miguel usiłuje zgłębić tajemnice rodzinnej legendy.',
                    'link_grafika' => 'storage/img/mk6.jpg',
                    'link_film' => 'https://www.youtube.com/embed/9JZ1nVH-dzg',
                    'cena' => '15',
                ],
                [
                    'tytul' => 'Psychoza',
                    'rezyser' => 'Alfred Hitchcock',
                    'genres_id' => '5',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '1980',
                    'czas_trwania' => '109',
                    'ocena' => '8.1',
                    'opis' => 'Dziewczyna uciekająca ze skradzionymi pieniędzmi zatrzymuje się w pensjonacie prowadzonym przez młodego Normana Batesa.',
                    'link_grafika' => 'storage/img/mk7.jpg',
                    'link_film' => 'https://www.youtube.com/embed/5Vl7Fq-CDzY',
                    'cena' => '19',
                ],
                [
                    'tytul' => 'Incepcja',
                    'rezyser' => 'Christopher Nolan',
                    'genres_id' => '3',
                    'produkcja' => 'Wielka Brytania',
                    'rok_produkcji' => '2010',
                    'czas_trwania' => '148',
                    'ocena' => '7.2',
                    'opis' => 'Czasy, gdy technologia pozwala na wchodzenie w świat snów. Złodziej Cobb ma za zadanie wszczepić myśl do śpiącego umysłu.',
                    'link_grafika' => 'storage/img/mk8.jpg',
                    'link_film' => 'https://www.youtube.com/embed/zrPGHWiZVVU',
                    'cena' => '18',
                ],
                [
                    'tytul' => 'Kac Vegas',
                    'rezyser' => 'Todd Phillips',
                    'genres_id' => '6',
                    'produkcja' => 'Niemcy',
                    'rok_produkcji' => '2009',
                    'czas_trwania' => '100',
                    'ocena' => '7.3',
                    'opis' => 'Czterech przyjaciół spędza wieczór kawalerski w Las Vegas. Następnego dnia okazuje się, że zgubili pana młodego i nic nie pamiętają.',
                    'link_grafika' => 'storage/img/mk9.jpg',
                    'link_film' => 'https://www.youtube.com/embed/wTKYkKErHGc',
                    'cena' => '22',
                ],
                [
                    'tytul' => 'Jak Wytresować Smoka',
                    'rezyser' => 'Chris Sanders',
                    'genres_id' => '4',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2010',
                    'czas_trwania' => '98',
                    'ocena' => '7.9',
                    'opis' => 'Chuderlawy Wiking przewróci porządek w wiosce, kiedy zamiast zabić w ramach inicjacji jakiegoś smoka, zaprzyjaźni się z najgroźniejszym z nich.',
                    'link_grafika' => 'storage/img/mk10.jpg',
                    'link_film' => 'https://www.youtube.com/embed/xhp_IKFt2yY',
                    'cena' => '23',
                ],
                [
                    'tytul' => 'Przygody Tintina',
                    'rezyser' => 'Steven Spielberg',
                    'genres_id' => '8',
                    'produkcja' => 'Nowa Zelandia',
                    'rok_produkcji' => '2011',
                    'czas_trwania' => '107',
                    'ocena' => '7.0',
                    'opis' => 'Reporter Tintin, kapitan Baryłka oraz pies Miluś wyruszają na poszukiwania zatopionego okrętu ze skarbem. Ich plany usiłuje pokrzyżować niegodziwy Sacharyna.',
                    'link_grafika' => 'storage/img/mk11.jpg',
                    'link_film' => 'https://www.youtube.com/embed/29onl-Zh2CQ',
                    'cena' => '20',
                ],
                [
                    'tytul' => 'Wizje',
                    'rezyser' => 'Kevin Greutert',
                    'genres_id' => '2',
                    'produkcja' => 'Japonia',
                    'rok_produkcji' => '2004',
                    'czas_trwania' => '97',
                    'ocena' => '6.2',
                    'opis' => 'W wypadku samochodowym mężczyzna traci córkę. Trzy lata później odkrywa tajemnicę związaną z przepowiedniami.',
                    'link_grafika' => 'storage/img/mk12.jpg',
                    'link_film' => 'https://www.youtube.com/embed/f9e-22jGd8Q',
                    'cena' => '24',
                ],
                [
                    'tytul' => 'Danza Macabra',
                    'rezyser' => 'Antonio Margheriti',
                    'genres_id' => '2',
                    'produkcja' => 'Włochy',
                    'rok_produkcji' => '1964',
                    'czas_trwania' => '82',
                    'ocena' => '6.5',
                    'opis' => 'Pełen emocji Horror w wykonaniu najlepszych gwiazd włoskiego kina',
                    'link_grafika' => 'storage/img/mk13.jpg',
                    'link_film' => 'https://www.youtube.com/embed/QQ_iExPd8zM',
                    'cena' => '18',
                ],
                [
                    'tytul' => 'Matrix',
                    'rezyser' => 'Lana Wachowski',
                    'genres_id' => '1',
                    'produkcja' => 'Australia',
                    'rok_produkcji' => '1999',
                    'czas_trwania' => '136',
                    'ocena' => '7.6',
                    'opis' => 'Haker komputerowy Neo dowiaduje się od tajemniczych rebeliantów, że świat, w którym żyje, jest tylko obrazem przesyłanym do jego mózgu przez roboty.',
                    'link_grafika' => 'storage/img/mk14.jpg',
                    'link_film' => 'https://www.youtube.com/embed/m8e-FF8MsqU',
                    'cena' => '25',
                ],
                [
                    'tytul' => 'Shrek',
                    'rezyser' => 'Andrew Adamson',
                    'genres_id' => '4',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2001',
                    'czas_trwania' => '90',
                    'ocena' => '7.8',
                    'opis' => 'By odzyskać swój dom, brzydki ogr z gadatliwym osłem wyruszają uwolnić piękną księżniczkę.',
                    'link_grafika' => 'storage/img/mk15.jpg',
                    'link_film' => 'https://www.youtube.com/embed/ooJJX3R42WM',
                    'cena' => '22',
                ],
                [
                    'tytul' => 'Nietykalni',
                    'rezyser' => 'Olivier Nakache',
                    'genres_id' => '6',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2011',
                    'czas_trwania' => '112',
                    'ocena' => '8.8',
                    'opis' => 'Sparaliżowany milioner zatrudnia do opieki młodego chłopaka z przedmieścia, który właśnie wyszedł z więzienia.',
                    'link_grafika' => 'storage/img/mk16.jpg',
                    'link_film' => 'https://www.youtube.com/embed/XglJSKew0QY',
                    'cena' => '25',
                ],
                [
                    'tytul' => 'Szósty Zmysł',
                    'rezyser' => 'Night Shyamalan',
                    'genres_id' => '5',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '1999',
                    'czas_trwania' => '107',
                    'ocena' => '7.4',
                    'opis' => 'Psycholog dziecięcy próbuje pomóc ośmioletniemu chłopcu widzącemu zmarłych poradzić sobie z tym niezwykłym darem.',
                    'link_grafika' => 'storage/img/mk17.jpg',
                    'link_film' => 'https://www.youtube.com/embed/DYpcbmcabvU',
                    'cena' => '19',
                ],
                [
                    'tytul' => 'Pianista',
                    'rezyser' => 'Roman Polański',
                    'genres_id' => '7',
                    'produkcja' => 'Polska',
                    'rok_produkcji' => '2002',
                    'czas_trwania' => '150',
                    'ocena' => '8.3',
                    'opis' => 'Podczas drugiej wojny światowej Władysław Szpilman, znakomity polski pianista, stara się przeżyć w okupowanej Warszawie.',
                    'link_grafika' => 'storage/img/mk18.jpg',
                    'link_film' => 'https://www.youtube.com/embed/K8DVwuXIx2E',
                    'cena' => '26',
                ],
                [
                    'tytul' => 'Bękarty Wojny',
                    'rezyser' => 'Quentin Tarantino',
                    'genres_id' => '7',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2009',
                    'czas_trwania' => '153',
                    'ocena' => '8.0',
                    'opis' => 'W okupowanej przez nazistów Francji oddział złożony z Amerykanów żydowskiego pochodzenia planuje zamach na Hitlera.',
                    'link_grafika' => 'storage/img/mk19.jpg',
                    'link_film' => 'https://www.youtube.com/embed/bUJPKAjAi-M',
                    'cena' => '20',
                ],
                [
                    'tytul' => 'Dzień Świra',
                    'rezyser' => 'Marek Koterski',
                    'genres_id' => '6',
                    'produkcja' => 'Polska',
                    'rok_produkcji' => '2002',
                    'czas_trwania' => '93',
                    'ocena' => '7.8',
                    'opis' => 'Adaś Miauczyński, 49-letni rozwiedziony polonista, żyje w kręgu swoich natręctw, nie potrafiąc wyrwać się z nudy i rutyny dnia codziennego.',
                    'link_grafika' => 'storage/img/mk20.jpg',
                    'link_film' => 'https://www.youtube.com/embed/lERimQ1dyos',
                    'cena' => '17',
                ],
                [
                    'tytul' => 'Sherlock Holmes',
                    'rezyser' => 'Guy Ritchie',
                    'genres_id' => '8',
                    'produkcja' => 'Niemcy',
                    'rok_produkcji' => '2009',
                    'czas_trwania' => '128',
                    'ocena' => '7.7',
                    'opis' => 'Najsłynniejszy detektyw Sherlock Holmes z nieodłącznym przyjacielem dr. Watsonem szukają sprawcy rytualnych morderstw.',
                    'link_grafika' => 'storage/img/mk21.jpg',
                    'link_film' => 'https://www.youtube.com/embed/IrBKwzL3K7s',
                    'cena' => '22',
                ],
                [
                    'tytul' => 'Infiltracja',
                    'rezyser' => 'Martin Scorsese',
                    'genres_id' => '5',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2006',
                    'czas_trwania' => '152',
                    'ocena' => '8.0',
                    'opis' => 'Tajny policjant w szeregach grupy przestępczej i informator mafii w bostońskiej jednostce dochodzeniowej toczą ze sobą śmiertelną rozgrywkę.',
                    'link_grafika' => 'storage/img/mk22.jpg',
                    'link_film' => 'https://www.youtube.com/embed/t0yIaHJlq0I',
                    'cena' => '23',
                ],
                [
                    'tytul' => 'Epoka Lodowcowa',
                    'rezyser' => 'Chris Wedge',
                    'genres_id' => '4',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2002',
                    'czas_trwania' => '81',
                    'ocena' => '7.6',
                    'opis' => 'W czasie wielkiej migracji zwierząt tygrys szablozębny, mamut i leniwiec starają się oddać ludzkie dziecko jego plemieniu.',
                    'link_grafika' => 'storage/img/mk23.jpg',
                    'link_film' => 'https://www.youtube.com/embed/OSimPIiZHxE',
                    'cena' => '22',
                ],
                [
                    'tytul' => 'Jestem Legendą',
                    'rezyser' => 'Francis Lawrence',
                    'genres_id' => '2',
                    'produkcja' => 'USA',
                    'rok_produkcji' => '2007',
                    'czas_trwania' => '101',
                    'ocena' => '7.5',
                    'opis' => 'Tajemniczy wirus wymordował lub zamienił w krwiożercze bestie prawie całą ludzkość. Samotny naukowiec Robert Neville poszukuje szczepionki, by odwrócić mutację.',
                    'link_grafika' => 'storage/img/mk24.jpg',
                    'link_film' => 'https://www.youtube.com/embed/ewpYq9rgg3w',
                    'cena' => '24',
                ],
                [
                    'tytul' => 'Kiler',
                    'rezyser' => 'Juliusz Machulski',
                    'genres_id' => '6',
                    'produkcja' => 'Polska',
                    'rok_produkcji' => '1997',
                    'czas_trwania' => '104',
                    'ocena' => '7.7',
                    'opis' => 'Jerzy Kiler, warszawski taksówkarz, przypadkowo zostaje wzięty za płatnego zabójcę i umieszczony w areszcie. Wyciąga go stamtąd boss świata przestępczego, który oferuje mu nowe zadanie.',
                    'link_grafika' => 'storage/img/mk25.jpg',
                    'link_film' => 'https://www.youtube.com/embed/0QsgQgT0O5E',
                    'cena' => '18',
                ]
            ],
            'tytul'
        );
    }
}
